version: '3.9'
services:
  app:
    container_name: node_notebook
    restart: always 
    build: . 
    ports: 
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    - "27017:27017"