version: '3'
services:
  api:
    build: .
    restart: always 
    depends_on:
      - mongo
    volumes:
      - . :/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    - "27017:27017"